version: "3.8"

services: 
    app:
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - 60000:60000
        volumes: 
            - -:/IntelliScout
            - '/IntelliScout/node_modules'
        depends_on: 
            -mysql_server

mysql_server:
    image: mysql:8.0
    environment: 
        - MYSQL_DATABASE = scouts
        - MYSQL_USER = root
        - MYSQL_PASSWORD = root
        - MYSQL_ROOT_PASSWORD = root
        